name: maven_bump
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - release

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - run: npx @dwmkerr/standard-version --packageFiles pom.xml --bumpFiles pom.xml -y 
