name: "tag"

on:
  push:
    branches:
      - release/**
      - release

jobs:
  bump-version:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Configure committer
        run: |
          git config user.name "github-actions"
          git config user.email "<41898282+github-actions[bot]@users.noreply.github.com>"
      - name: Bump version
        run: |
          bash cd ${{ github.workspace }}
          bash ls -la
          bash ./bump_version.sh
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          tags: true